ahmet/awesome-web3

- README.md
I add [thirdweb](https://thirdweb.com) to the platform as a service section of the list.
> add: thirdweb to platform as a service

- README.md
This will add the following Robot Framework toolkit that combines Truffle and Hardhat with [RPA](https://robotframework.org/rpa/).
https://github.com/jg8481/Robot-Framework-Solidity-Testing-Toolkit
> Add Robot Framework Solidity Testing Toolkit

- mlc_config.json
Some sites return HTTP 403 even though they work as expected when an ordinary user agent visits the page.
> Update markdown link checker config

- README.md
Adds [libethc](https://github.com/mhw0/libethc) into the `C/C++` section.
> Add libethc to C/C++

- README.md
Added Solana Playground which was not present in the list of development environments where other online IDEs were present.
> Add Solana Playground to Development Environment

- README.md
Add link to rivet.cloud node provider service to the Platform as a Service section
> Add rivet.cloud to Platform as a Service

- README.md
Adding [Ethereum-Ecosystem](https://www.ethereum-ecosystem.com/) to the list - an Unofficial Ecosystem page for Ethereum and its Layer 2s featuring 900+ dApps and tools across Optimism, Base, Starknet and more.
> Add Ethereum-Ecosystem

- README.md
Minting.tools is a free, no-code, ERC20 token generator and deployer. It uses OpenZeppelin smart-contracts to create tokens for people. 100% client-side, with 0 cost.
> Add Minting.tools

- README.md
This resolves the issue https://github.com/ahmet/awesome-web3/issues/397
> tutorial: Build a blockchian from scratch in Go with gRPC

- README.md
I noticed a typo in the "Polybase" section under the "Database" category. The word "Firstore" was incorrectly used, and it should be "**Firestore**." This correction ensures that the description accurately refers to the Firebase Firestore database.
Here’s the updated sentence:
> "Polybase is a drop-in replacement for Firebase, Firestore alongside 10x better db permissions with ZK + Wallet Auth."
> docs: Fix Typo in "Polybase" Database Section Update README.md

- README.md
I noticed that the links to `https://nftschool.dev/` and `https://learn.figment.io/` are no longer active. To keep the resource list up-to-date and reliable, I’ve removed these links.  
This ensures that users won’t encounter dead links while exploring the content. Let me know if there are any other updates needed!
> docs: remove broken links to NFT School and Figment Learn

- pages/index.js
Hey! I noticed that `join` was used in `getStaticProps`, but it wasn’t imported, which would throw a `ReferenceError`.
Just added `import { join } from 'path'`, and everything should work smoothly now.
> fix: missing `join` import in `getStaticProps`

- README.md
`https://rollup.id/` no longer exists, so I removed it to keep the links relevant and avoid broken references.
> docs: Removed dead link to rollup.id

- README.md
The link to `https://basement.dev/` has been removed since the site no longer exists.
> Remove defunct basement.dev link

- README.md
Adding [Web3 Antivirus](https://web3antivirus.io/) to the Risk Management list
> Add Web3 Antivirus

- README.md
I removed the link to [https://meson.network/](https://meson.network/) since the project is no longer active and the site is down.
> Remove dead link to Meson Network

- README.md
Noticed that the link to `https://minting.tools` no longer works — the domain seems to be down or gone entirely.
I’ve removed the reference to avoid confusion or dead-end navigation.
> docs: remove broken link to minting.tools

- README.md
the link to the wagmi repo was outdated — it pointed to `tmm/wagmi`, which is no longer correct.
updated it to `wevm/wagmi` so it now links to the official repository.
> docs: fix incorrect wagmi GitHub URL

- README.md
Saw the IPFS link was outdated - updated it to the correct one: https://ipfs.tech/
> docs: Fixed incorrect IPFS link

- README.md
**Description:**  
Noticed a small typo in the Uniswap section—missing article “a” in the description.
> docs: fix typo and improve Uniswap protocol description

- README.md
**Description:**  
Noticed a couple typos while reading through the docs:
- corrected “WomenBuildlWeb3” to “WomenBuildWeb3”
- “Liverpeer.js” to “Livepeer.js”.
thanks!
> docs: Fix typos in community and library names

- .github/workflows/checks.yml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
> ci: bump actions/checkout to v4

- README.md
Noticed a small grammatical error in the Livepeer description—missing article before "Ethereum-based protocol."
Updated it to say "**an Ethereum-based protocol**" for clarity and correctness.
> docs: Fix minor grammar mistake in Livepeer description

- .github/workflows/checks.yml
Potential fix for [https://github.com/ahmet/awesome-web3/security/code-scanning/2](https://github.com/ahmet/awesome-web3/security/code-scanning/2)
To fix the issue, we will add a `permissions` block at the workflow level (root) to restrict the permissions of the `GITHUB_TOKEN`. Since the workflow only checks markdown links, it only requires read access to the repository contents. We will set `contents: read` as the minimal required permission.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 2: Workflow does not contain permissions

- README.md
Adds ipfs-to-swarm, a CLI tool for migrating data from IPFS to Swarm, to the Tutorials section. Supports folder uploads and highlights structural differences between the two systems.
> Add ipfs-to-swarm
