README.md
=> update meson network

README.md
You could have a check to the readme, https://github.com/SoxZz5/next-web3-boilerplate
It's a boilerplate with many lib easy to use for starting with walletconnect or metamask, some configurable env var and using useDapp to handle contract interaction with a session cache using next-auth and some basic lib for design reactMUI
=> Add my boilerplate to the list

README.md
=> Added DeFi Developer Roadmap

README.md
New category No Code
The no code development is increasing exponentially, it has more power than you may imagine, so I think it is worth it to add this new category.
I will start with Polkadot.js plugin that was built with the [official help from Web3 Foundation](https://twitter.com/Web3foundation/status/1493216414290919424)  for one of the biggest no code platform bubble.io
=> Add nocode-polkadot

README.md
=> Added orbitdb and gun as per issue #9

README.md
Another powerful and free no code plugin for bubble.io.
The plugin was built in collaboration with Rarible team.
=> Add rarible-sdk

README.md
Add ZilPay (Zilliqa Wallet) No Code plugin
=> Add zillpay-nocode

README.md
=> Updated ZilPay description

README.md
=> Added Chainstack to Platform as a Service section

README.md
=> Added LearnWeb3 DAO to Tutorial section

README.md
=> Added Questbook to Tutorial Section

README.md
=> Added Cadena to Tutorial section.

README.md
=> Added Smart Contract Programmer to YouTube Channel

README.md
=> Added Alchemy to YouTube Channel section

README.md
=> Added Blog to Tutorial section

README.md
=> Added Austin Griffith to YouTube Channel section

README.md
=> Added Moralis Web3 to YouTube Channel section

README.md
Added ChainJet to the No Code section.
=> Add ChainJet to No Code section

README.md
=> Added Block Explorer to YouTube Channel section

README.md
=> Added Figment Learn to Tutorial Section

README.md
=> Added Odyssey to Tutorial Section

README.md
=> Added Bankless Academy to Tutorial Section

README.md
=> add: awesome list and yt channel

README.md
web3byexample is example code of how to implement Ethers with JavaScript
=> Added web3byexample

README.md
=> Added Foundry to Development Environment Section

README.md
=> Added Aave Protocol to Protocol Section

README.md
=> Added Lens Protocol to Awesome List Section

README.md
=> Added Alchemy University to Tutorial Section

README.md
=> Added Chainlink to Open Source Project Section

README.md
=> Added HashLips NFT to YouTube Channel Section

README.md
Add Payroll in the Other section
=> Add Payroll

README.md
Add the db3 network repo to the awesome list
=> Add db3 network to the list

README.md
=> Added How To Web3 to Tutorial Section

README.md
=> Added RPC Nodes to Awesome List Section

README.md
=> Added Web3 Security to Awesome List Section

README.md
=> Added SmartWeave to Protocol Section

README.md
=> Added XMTP to Awesome List Section

README.md
=> Added Turbo ETH to Boilerplate Section

README.md
=> Add Developer DAO Academy to Tutorial Section

README.md
=> Add WalletConnect to no code section

README.md
=> Add Metaschool to Tutorial Section

README.md
=> Add WeaveDB to Database Section

README.md
=> Add ensjs to JavaScript Section

README.md
=> Add Embark to Development Environment Section

README.md
=> Added "Awesome Farcaster" and "Launchcaster" links

README.md
=> Add ethereum-boilerplate to Boilerplate Section

README.md
=> Add The Graph to Protocol Section

README.md
=> Add Push to Protocol Section

README.md
=> Add Ceramic Network to Protocol Section

README.md
=> Add Lens.js to JavaScript Section

README.md
=> Add bee-js to JavaScript Section

README.md
=> Add Polkadot to Protocol Section

README.md
=> Add livepeer.js to JavaScript Section

README.md
=> Add Blockend to Developer Roadmap Section

README.md
=> Add Blockchain Threat Intelligence Newsletter

README.md
=> Add zkSync to Protocol Section

README.md
=> Add NFT to Awesome List Section

README.md
=> Add Ankr to Platform as a Service Section

README.md
=> Add solana-web3.js to JavaScript Section

README.md
=> Add GetBlock to Platform as a Service Section

README.md
=> Add Uniswap to Protocol Section

README.md
Delphi Media's YouTube channel has changed its URL, so I've updated.
=> Updated Delphi Media link

README.md
=> Add District0x to Tutorial Section

README.md
=> Add Arweave to Protocol Section

README.md
=> Add NEAR to Protocol Section

README.md
=> Add Whiteboard Crypto to YouTube Channel Section

README.md
=> Add Livepeer to Protocol Section

README.md
=> Add Solidity to Open Source Project Section

README.md
=> Add react-moralis to Open Source Project Section

README.md
=> Add Token Economy Book to Book Section

README.md
=> Add Jarrod Watts to YouTube Channel Section

README.md
=> Add simplehash to tutorials

README.md
Basement is a platform to query and index on-chain data on EVM based chains
=> Add Basement to platforms

README.md
=> Add web3.py to Python Section

README.md
=> Add create-web3-dapp to Boilerplate Section

README.md
=> add Blockchain to Awesome List

README.md
=> add ethereum-security to Awesome List

README.md
=> add Solana to Open Source Project

README.md
=> add seaport-js to JavaScript

README.md
=> add Foundry to Awesome List

README.md
=> add js-algorand-sdk to JavaScript

README.md
=> Add Neo to Open Source Project

README.md
=> Add prb-test to Testing

README.md
=> Add The Book of Swarm to Book

README.md
=> Add Vyper to Awesome List

README.md
=> Add Hashing Bits to Newsletter

README.md
=> Remove openquest broken link

README.md
=> Add nexth to Boilerplate

README.md
=> Add starknet.js to JavaScript

README.md
=> Add Arweave to Awesome List

README.md
=> Add StarkNet to Awesome List

README.md
=> Add notify to JavaScript

README.md
=> Add Compound to Protocol

README.md
=> Add Yield to Protocol

README.md
=> Add fabric to Open Source Project

README.md
=> Add web3swift to Open Source Project

README.md
=> Add Huff to Awesome List

README.md
=> Add Euler to Protocol

README.md
=> Add Unitas to Protocol

README.md
=> Add Ocean Protocol to Protocol

README.md
=> Add NFT School to Tutorial

README.md
=> Add WebThree.FYI to Newsletter

README.md
=> Add Fuel to Open Source Project

README.md
=> Add Staking Academy to Tutorial

README.md
=> Add Vyper to Tutorial

README.md
=> Adding dynamic.xyz to the list

README.md
=> Add walletOS

README.md
Adding two open source projects as well as one development environment (SDK) to the lists.
=> Add kryptokrona-kotlin-sdk, hugin-desktop and hugin-mobile

README.md
=> Adding Rollup id to the list

README.md
=> Add Zero Knowledge to Awesome List

README.md
=> fix BuidlGuidl Newsletter link

README.md
=> add Vyper by Example to Sample Code

README.md
=> add Blockchain Scalability to Awesome List

README.md
=> add MakerDAO to Awesome List

README.md
=> Add  Aztec Network to Protocol

README.md
=> Add  sequence.js to JavaScript

README.md
=> add IPOR to Protocol

README.md
=> add Vyper to Reference

README.md
=> add  Ajna Protocol to Protocol

README.md
add https://kriptonio.com/, web3 infrastructure and development platform
=> add Kriptonio

README.md
=> add Synapse to Protocol

README.md
=> add CREATE2 Deployer

README.md
=> add Solady

README.md
Adding Wriggly.io to tutorial section.
Wriggly is a web3 learning platform to practice smart contract coding challenges and enhance your blockchain skills. Wriggly wants to change the way we learn blockchain and create a collaborative platform for developers to learn.
https://wriggly.io/
=> [Wriggly] Adding Wriggly to Tutorial Projets

README.md
=> Add dapp-starter-template 

README.md
Added Ethora web3 engine to the list of open-source projects.
=> Ethora - Open source web3 engine

README.md
Router Protocol bridges layer 1 and layer 2 blockchains, enabling seamless cross-chain liquidity migration in DeFi. It facilitates token transfers between chains and cross-chain execution of operations.
Added Router Protocol to Protocol Section
=> Added Router Protocol to list of Protocols

README.md
=> add Yul By Example

README.md
Added new DevOps Section to Readme
Added Cannon to the list of tools under new DevOps section
- [x ] The URL is not already present in the list (check with CTRL/CMD+F in the raw markdown file).
- [x ] Each description starts with an uppercase character and ends with a period.<br>Example: `solc-js - JavaScript bindings for the compiler.`
- [x ] Drop all `A` / `An` prefixes at the start of the description.
=> Add awesome-cannon

README.md
Add Indexed.xyz.
I created a new section called Datasets, I'm open to adjusting the name or placing this link somewhere that it fits. I have a few other public datasets to add as well, but wanted to stick to one link at a time!
=> Add Indexed.xyz

README.md
Added [Tenderly](https://tenderly.co) to the list of products under Platform as a Service section.
=> Add Tenderly to Platform as a Service

README.md
Add [Tenderly DevNets](https://docs.tenderly.co/devnets/intro-to-devnets) to `Development Environment` section.
=> Add Tenderly DevNets to Development Environment

README.md
Proposes [dAppling Network](https://dappling.network) as a web hosting platform
=> add dAppling network

README.md
=> Add Apillon.io

README.md
I added the link to the materials about the Kiwi Protocol - crypto-oriented HackerNews dapp & P2P protocol.
=> Add awesome-kiwi

README.md
Adding important resources about account abstraction (ERC-4337, ERC-1271)
=> Add awesome-account-abstraction, signature-validator

README.md
adding Ambire Wallet as the first open source consumer-centric account abstraction wallet for EVM chains
=> Add Ambire Wallet to open source projects

README.md
=> Add Mobula to Open-source

README.md
I have included Cyfrin Updraft site to the list of tutorials.
=> Add Cyfrin Updraft

README.md
Add Coinbase's OnchainKit to the list of JavaScript resources
=> Add OnchainKit

README.md
=> Adding Tatum under Providers as Service

README.md
=> add @kolirt/vue-web3-auth

README.md
Token Icons is an open-source MIT licensed project that provides optimized SVGs for all the crypto currency icons in the top 2500 by market cap. The @token-icons/react npm package provides React components for the token icons and @token-icons/core provides optimized SVGs.
You can see the icons on: https://tokenicons.io
=> add @token-icons

README.md
Adding eRPC as a proxy/caching tool for rpc node providers (written in golang)
=> docs: add eRPC

README.md
Hi, thanks for maintaining this awesome list! And including useWeb3 and Nexth already :)
Suggesting another open-source tool I've built to be included in your list. Thanks!
=> add ethgastracker

README.md
=> Add polkadart

README.md
=> add golang Threshold Signature Scheme, for ECDSA and EDDSA

README.md
Add awesome-avalanche repo
- [ x] The URL is not already present in the list (check with CTRL/CMD+F in the raw markdown file).
- [ x] Each description starts with an uppercase character and ends with a period.<br>Example: `solc-js - JavaScript bindings for the compiler.`
- [ x] Drop all `A` / `An` prefixes at the start of the description.
=> Add Avalanche Ecosystem

README.md
Add link to [Konkret Wallet](https://codeberg.org/konkret/konkret-wallet)
=> Add Konkret Wallet

CONTRIBUTING.md
Spotted and corrected a small typo - changed "Thanks you" to "Thank you".
=> docs: Fix typo in user-facing message

README.md
This pull request fixes the formatting or typo of the word "blockchain" in the README.md file in the Odyssey platform description section.
=> Fix blockchain formatting in README.md

README.md
=> Add Mindlyn

README.md
Add Ormi Labs - real-time smart contract data across 70+ chains
=> Add Ormi Labs - real-time blockchain data and subgraphs
